Add tests and deploy
Vladimir-prog-java/react-burger pull request #6
Opened 2023-05-01 14:05 UTC by Vladimir-prog-java

2023-05-01 14:50 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Все Jest тесты (33 шт) проходят успешно
- Избежали дублирования кода в тестах
- Для одного теста использовали один `expect` 

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- в Cypress необходимо протестировать функционал оформления заказа и открытия и закрытия модального окна.
- Необходимо в Readme.md добавить ссылку на деплой проекта

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-02 17:43 UTC, Vladimir-prog-java commented
Спасибо за ревью. Не совсем понял, почему-то в прошлый раз readme не обновилась, хотя ссылку добавлял. У меня проблема :((( Жесткий диск на рабочем компе приказал долго жить, осталась машина с Windows 7 но на ней 16 нода не поедет :(

2023-05-03 09:58 UTC, andryxxa93 commented
Вы отлично поработали!
Работа принята. Удачи вам и успехов!

2023-05-03 09:59 UTC, andryxxa93 commented
> Спасибо за ревью. Не совсем понял, почему-то в прошлый раз readme не обновилась, хотя ссылку добавлял. У меня проблема :((( Жесткий диск на рабочем компе приказал долго жить, осталась машина с Windows 7 но на ней 16 нода не поедет :(

Если проблема с диском - это надолго, можете попробовать себе вместо windows 7 установить ubuntu - не требовательная система и поддерживает VSC.

2023-05-03 16:28 UTC, merged